Refactor app

diff --git a/run b/run
--- a/run
+++ b/run
@@ -82,7 +82,7 @@ task_docker_build() {
 # Push production docker image to registry
 task_docker_push() {
     if echo "$tag" | grep "dirty" >/dev/null; then
-        print error "image tag is dirty. please commit the changes and re-build the image."
+        print error "Image tag is dirty. Please commit the changes and re-build the image."
         return 1
     fi
     if [[ -n "$DOCKERHUB_USERNAME" && -n "$DOCKERHUB_PASSWORD" ]]; then
@@ -92,7 +92,7 @@ task_docker_push() {
     docker push "$repository:$tag"
     docker push "$repository:latest"
     echo
-    print info "the following images were pushed to registry:
+    print info "The following images were pushed to registry:
     - $repository:$tag
     - $repository:latest"
 }
@@ -103,10 +103,10 @@ task_watch() {
     local build_cmd="go build --ldflags=\"-X $PACKAGE_NAME/internal/config.BuildId=$APP_NAME.$APP_VERSION-dev\" --race -o $tmp_dir/main  ."
 
     if ! command -v air &>/dev/null; then
-        print loading "installing air..."
+        print loading "Installing air..."
         go install github.com/air-verse/air@latest
     fi
-    print loading "starting development server..."
+    print loading "Starting development server..."
     # build.kill_delay is in nanoseconds
     air --tmp_dir="$tmp_dir" --build.cmd "$build_cmd" --build.bin "$tmp_dir/main" --build.delay 0 --build.kill_delay 10000000000 \
         --build.include_ext "go,tmpl,env,json" --build.send_interrupt true --log.main_only true
@@ -120,33 +120,33 @@ task_build() {
         -ldflags='-s -w -X $PACKAGE_NAME/internal/config.BuildId=$build_id -extldflags \"-static\"' \
         --trimpath -o $build_path ."
 
-    print loading "building app..."
+    print loading "Building app..."
     if go generate ./...; then
-        print success "openapi docs generated"
+        print success "Swagger docs generated"
     else
-        print error "failed to generate openapi docs"
+        print error "Failed to generate swagger docs"
         return 1
     fi
 
     if ! eval "$build_cmd"; then
-        print error "build failed"
+        print error "Build failed"
         return 1
     fi
 
     if file "$build_path" | grep "dynamically linked" >/dev/null; then
-        print error "binary is still dynamically linked."
+        print error "Binary is still dynamically linked."
         file "$build_path"
         return 1
     fi
 
-    print success "build generated"
-    print debug "build id: $build_id"
+    print success "Build succesful"
+    print debug "Build id: $build_id"
 }
 
 # Run go app build
 task_start() {
     if [[ ! -x "$build_path" ]]; then
-        print error "build not found."
+        print error "Build not found."
         return 1
     fi
     "$build_path"
@@ -154,64 +154,63 @@ task_start() {
 
 # Run tests
 task_test() {
-    print loading "running tests..."
+    print loading "Running tests..."
     go test --race --count=2 -v ./...
 }
 
 # Run tests and show coverage
 task_test_cover() {
-    print loading "running tests and generating coverage report..."
+    print loading "Running tests and generating coverage report..."
     SECRETS_FILE=../../secrets.json go test --race --coverprofile=./tmp/coverage.out ./... && go tool cover --html=./tmp/coverage.out
 }
 
 # Run benchmarks
 task_benchmark() {
-    print loading "running benchmarks..."
+    print loading "Running benchmarks..."
     SECRETS_FILE=../../secrets.json go test --race --count=2 -v --benchmem --bench=. ./...
 }
 
 # Clean go mod & cache & remove build artifacts
 task_clean() {
-    print loading "cleaning..."
+    print loading "Cleaning..."
     go mod tidy -v
     go clean --cache
     rm -rf ./bin ./.tmp
-    print success "cleaned up"
+    print success "Cleaned up"
 }
 
 # Generate pprof profile
 task_pprof() {
-    print loading "generating pprof profile..."
+    print loading "Generating pprof profile..."
     if [[ -z "$PORT" ]]; then
-        print error "port is not set"
+        print error "PORT is not set"
         return 1
     fi
-    curl "http://localhost:${PORT}/debug/pprof/profile?seconds=30" >default.pgo && print success "pprof profile generated"
+    curl "http://localhost:${PORT}/debug/pprof/profile?seconds=30" >default.pgo && print success "Pprof profile generated"
 }
 
 # Create a git checkpoint and push to origin
 task_checkpoint() {
-    if (! prompt "create git checkpoint and push changes to origin?") || (! task_build && ! prompt "still continue?"); then
-        print "quitting..."
+    if (! prompt "Create git checkpoint and push changes to origin?") || (! task_build && ! prompt "Still continue?"); then
+        print "Quitting..."
         return 1
     fi
     if ! (git add . && git commit -m "Checkpoint - $(date -u)" && git push); then
-        print error "failed to create checkpoint"
+        print error "Failed to create checkpoint"
         return 1
     fi
-    print success "checkpoint created"
+    print success "Checkpoint created"
 }
 
 # Upgrade dependencies
 task_upgrade_deps() {
-    print loading "checking for updates..."
+    print loading "Checking for updates..."
     if ! go get -u ./...; then
-        print error "failed to upgrade packages"
+        print error "Failed to upgrade packages"
         return 1
     fi
-    print success "upgraded minor/patch versions of packages"
-    print debug "to upgrade major versions, run 'go get -u <package>@<version>' for each package manually"
-
+    print success "Upgraded minor/patch versions of packages"
+    print debug "To upgrade major versions, run 'go get -u <package>@<version>' for each package manually"
 }
 
 if [[ -z "$(declare -F "task_$1")" ]]; then
