Upgrade deps

diff --git a/run b/run
--- a/run
+++ b/run
@@ -16,24 +16,23 @@ CONFIG_FILE=${CONFIG_FILE:-"config.json"}
 set +o allexport
 
 print() {
-    declare -A colors=(["debug"]="30" ["loading"]="30" ["info"]="34" ["success"]="32" ["warn"]="33" ["error"]="31")
+    declare -A colors=(["debug"]="30" ["loading"]="30" ["info"]="37" ["success"]="32" ["warn"]="33" ["error"]="31")
     local prefix
     local suffix
 
     case "$1" in
-    "debug") prefix="⚙ " ;;
+    "debug") prefix="⚙" ;;
     "loading")
-        prefix="⧗ "
+        prefix="⧗"
         suffix="..."
         ;;
-    "info") prefix="➤ " ;;
-    "success") prefix="✔ " ;;
-    "warn") prefix="⚠ " ;;
-    "error") prefix="✗ " ;;
-    *) prefix=" " ;;
+    "info") prefix="➤" ;;
+    "success") prefix="✔" ;;
+    "warn") prefix="⚠" ;;
+    "error") prefix="✗" ;;
     esac
 
-    local text="$prefix$2$suffix"
+    local text="$prefix $2$suffix"
 
     if tput colors &>/dev/null; then
         printf "\x1b[0;%sm%s\x1b[0m\n" "${colors[$1]}" "${text:-$1}"
@@ -104,8 +103,14 @@ build() {
         return 1
     fi
 
+    print loading "Generating OpenAPI docs"
+    if ! go generate ./...; then
+        print error "OpenAPI docs generation failed"
+        return 1
+    fi
+
     print loading "Building app"
-    if ! go generate ./... || ! eval "$build_cmd"; then
+    if ! eval "$build_cmd"; then
         print error "Build failed"
         return 1
     fi
@@ -116,8 +121,7 @@ build() {
         return 1
     fi
 
-    print success "Build generated"
-    print debug "App version: $APP_VERSION"
+    print success "Build generated ($APP_VERSION)"
 }
 
 start() {
@@ -178,13 +182,13 @@ print_menu() {
 ➤ watch        - Run live development server
 ➤ build        - Build go app for production release and generate OpenAPI docs
 ➤ start        - Run go app binary
-➤ docker-watch - Run live development server in docker
-➤ docker-build - Build the Docker image for production
-➤ docker-push  - Push the production docker image to registry
-➤ test         - Run tests (pass --cover to show coverage report)
+➤ docker-watch - Run live development server using docker compose
+➤ docker-build - Build the production docker image
+➤ docker-push  - Push the production docker image to remote registry
+➤ test         - Run tests (pass --coverage for coverage report)
 ➤ benchmark    - Run benchmarks
 ➤ checkpoint   - Create a git checkpoint and push changes to origin
-➤ pprof        - Start pprof profile
+➤ pprof        - Create pprof profile
 ➤ upgrade      - Upgrade dependencies
 
 Usage: $0 <task>"
@@ -210,7 +214,7 @@ case "$1" in
     docker_push
     ;;
 "test")
-    if [[ "$2" == "--cover" ]]; then
+    if [[ "$2" == "--coverage" ]]; then
         test_cover
     else
         test
