Checkpoint - Fri Oct 11 16:48:08 UTC 2024

diff --git a/run b/run
--- a/run
+++ b/run
@@ -25,7 +25,7 @@ print() {
     declare -A colors=(["debug"]="30" ["loading"]="36" ["info"]="37" ["success"]="32" ["warn"]="33" ["error"]="31")
     local prefix
     case "$1" in
-    "debug") prefix="• " ;;
+    "debug") prefix="⚙ " ;;
     "loading") prefix="⧗ " ;;
     "info") prefix="➤ " ;;
     "success") prefix="✔ " ;;
@@ -36,9 +36,9 @@ print() {
 
     local text="$prefix$2"
     if tput colors &>/dev/null; then
-        printf "\x1b[%sm%s\x1b[0m\n" "${colors[$1]:-white}" "$text"
+        printf "\x1b[%sm%s\x1b[0m\n" "${colors[$1]}" "${text:-$1}"
     else
-        printf "%s\n" "$text"
+        printf "%s\n" "${text:-$1}"
     fi
 }
 
@@ -52,7 +52,7 @@ print_menu() {
 
     mapfile -t tasks < <(printf "%s\n" "${tasks[@]}" | sort)
 
-    echo "Available tasks"
+    echo "Available tasks:"
     for task in "${tasks[@]}"; do
         echo "➤ $task"
     done
@@ -72,7 +72,7 @@ readonly repository
 readonly tag="$APP_VERSION"
 # Build docker image for release
 task_docker_build() {
-    if docker images | grep "$repository:$tag"; then
+    if docker images | grep "$repository:$tag" >/dev/null; then
         docker rmi "$repository:$tag" --force
     fi
     docker build --tag "$repository:$tag" --target production --platform linux/amd64 --build-arg BASE_IMAGE_TAG="$BASE_IMAGE_TAG" .
@@ -81,8 +81,8 @@ task_docker_build() {
 
 # Push production docker image to registry
 task_docker_push() {
-    if echo "$tag" | grep "dirty"; then
-        print error "image tag is dirty. Please commit the changes and re-build the image."
+    if echo "$tag" | grep "dirty" >/dev/null; then
+        print error "image tag is dirty. please commit the changes and re-build the image."
         return 1
     fi
     if [[ -n "$DOCKERHUB_USERNAME" && -n "$DOCKERHUB_PASSWORD" ]]; then
@@ -92,7 +92,7 @@ task_docker_push() {
     docker push "$repository:$tag"
     docker push "$repository:latest"
     echo
-    print info "The following images were pushed to registry:
+    print info "the following images were pushed to registry:
     - $repository:$tag
     - $repository:latest"
 }
@@ -106,6 +106,7 @@ task_watch() {
         print loading "installing air..."
         go install github.com/air-verse/air@latest
     fi
+    print loading "starting development server..."
     # build.kill_delay is in nanoseconds
     air --tmp_dir="$tmp_dir" --build.cmd "$build_cmd" --build.bin "$tmp_dir/main" --build.delay 0 --build.kill_delay 10000000000 \
         --build.include_ext "go,tmpl,env,json" --build.send_interrupt true --log.main_only true
@@ -118,8 +119,8 @@ task_build() {
     local build_cmd="CGO_ENABLED=0 go build \
         -ldflags='-s -w -X $PACKAGE_NAME/internal/config.BuildId=$build_id -extldflags \"-static\"' \
         --trimpath -o $build_path ."
-    print loading "building app..."
 
+    print loading "building app..."
     if go generate ./...; then
         print success "openapi docs generated"
     else
@@ -133,12 +134,12 @@ task_build() {
     fi
 
     if file "$build_path" | grep "dynamically linked" >/dev/null; then
-        print error "fatal: binary is still dynamically linked."
+        print error "binary is still dynamically linked."
         file "$build_path"
         return 1
     fi
 
-    print success "build successful"
+    print success "build generated"
     print debug "build id: $build_id"
 }
 
@@ -153,62 +154,68 @@ task_start() {
 
 # Run tests
 task_test() {
+    print loading "running tests..."
     go test --race --count=2 -v ./...
 }
 
 # Run tests and show coverage
 task_test_cover() {
+    print loading "running tests and generating coverage report..."
     go test --race --coverprofile=./tmp/coverage.out ./... && go tool cover --html=./tmp/coverage.out
 }
 
 # Run benchmarks
 task_benchmark() {
+    print loading "running benchmarks..."
     go test --race --count=2 -v --benchmem --bench=. ./...
 }
 
 # Clean go mod & cache & remove build artifacts
 task_clean() {
+    print loading "cleaning up..."
     go mod tidy -v
     go clean --cache
     rm -rf ./bin ./.tmp
-    print success "cleaned up successfully"
+    print success "cleaned up"
 }
 
 # Generate pprof profile
 task_pprof() {
-    curl "http://localhost:${PORT:-"8080"}/debug/pprof/profile?seconds=30" >default.pgo && print success "pprof profile generated successfully"
+    print loading "generating pprof profile..."
+    if [[ -z "$PORT" ]]; then
+        print error "port is not set"
+        return 1
+    fi
+    curl "http://localhost:${PORT}/debug/pprof/profile?seconds=30" >default.pgo && print success "pprof profile generated"
 }
 
 # Create a git checkpoint and push to origin
 task_checkpoint() {
-    if ! prompt "Create git checkpoint and push changes to origin?"; then
-        print info "quitting..."
+    if (! prompt "create git checkpoint and push changes to origin?") || (! task_build && ! prompt "still continue?"); then
+        print "quitting..."
         return 1
     fi
-    if ! task_build && ! prompt "Still continue?"; then
-        print info "quitting..."
+    if ! (git add . && git commit -m "Checkpoint - $(date -u)" && git push); then
+        print error "failed to create checkpoint"
         return 1
     fi
-    if git add . && git commit -m "Checkpoint at $(date -u)" && git push; then
-        print success "Checkpoint created successfully ✔"
-        return 0
-    fi
-    print error "Failed to create checkpoint"
+    print success "checkpoint created ✔"
 }
 
 # Upgrade dependencies
 task_upgrade_deps() {
-    if go get -u ./...; then
-        print success "✔ Upgraded minor/patch versions of packages successfully"
-        print info "To upgrade major versions, you have to run 'go get -u <package>@<version>' for each package manually"
-        return 0
+    print loading "checking for updates..."
+    if ! go get -u ./...; then
+        print error "failed to upgrade packages"
+        return 1
     fi
-    print error "failed to upgrade packages"
+    print success "upgraded minor/patch versions of packages"
+    print debug "to upgrade major versions, run 'go get -u <package>@<version>' for each package manually"
+
 }
 
 if [[ -z "$(declare -F "task_$1")" ]]; then
     print_menu
 else
-    print info "Executing task: $*"
     "task_$*"
 fi
